version: "2"

networks:
  dev-back:
    driver: bridge
  dev-front:
    driver: bridge

volumes:
  app_database:

services:
  api:
    build:
      context: ./Back/src
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnect=User ID=postgres;Password=postgres;Host=api_database;Port=5432;Database=FinanceiroAPI
    networks:
      - dev-back
    links:
      - api_database
    depends_on:
      - "api_database"

  api_database:
    image: postgres:latest
    container_name: api_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=FinanceiroAPI
    ports:
      - "5433:5432"
    expose:
      - "5433"
    networks:
      - dev-back
    volumes:
      - app_database:/var/lib/postgresql/data
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: 5s
  client:
    build:
      context: ./Front/FinanceWasm
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_URLS=http://*:5003
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - dev-front
